Repository gather-here/gather_here, pull requests merged in 2024-09, with the labels that each got.

#284 fix/chat_css_in_safari_and_firefox
  README.md
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
Labels: fix

#290 refactor: signupform페이지로 변경 #287
  src/app/(auth)/signup/page.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup02.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/Signup04.tsx
Labels: refactor

#291 Del/zustand
  src/app/(auth)/signup/page.tsx
  src/components/Common/Header/Header.tsx
  src/components/MyPage/Common/LeftNav.tsx
  src/components/MyPage/MyInfo/ProfileInfo.tsx
  src/components/MyPage/MyInfo/ProfilePicture.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup02.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/Signup04.tsx
  src/components/Signup/SigupForm.tsx
  src/hooks/useSelectJob.ts
  src/hooks/useSubmitProfile.ts
  src/provider/ContextProvider.tsx
  src/provider/UserContextProvider.tsx
  src/store/useSignupStore.ts
Labels: del

#302 Feature/gather hub
  package-lock.json
  package.json
  public/logos/gatherhere.svg
  public/logos/hi.png
  public/logos/hub1.png
  public/logos/hub2.png
  src/app/api/auth/callback/route.ts
  src/app/gatherHub/layout.tsx
  src/app/gatherHub/page.tsx
  src/app/globals.css
  src/components/Common/Header/Header.tsx
  src/components/GatherHub/JobDirectory.tsx
  src/components/GatherHub/MemberCard.tsx
  src/components/Login/LoginForm.tsx
  src/components/MainPage/NavTab/NavTabs.tsx
  src/components/Signup/Signup03.tsx
  src/provider/UserContextProvider.tsx
Labels: feature

#306 Feat/tanstack query
  src/app/api/auth/callback/route.ts
  src/app/gatherHub/page.tsx
Labels: update, feature

#311 feat/Scroll restoration
  package-lock.json
  src/app/api/auth/callback/route.ts
  src/app/gatherHub/page.tsx
  src/app/globals.css
  src/components/Common/Header/Header.tsx
  src/components/GatherHub/JobDirectory.tsx
  src/components/GatherHub/MemberCard.tsx
  src/components/MyPage/Common/LeftNav.tsx
  src/types/supabase.ts
Labels: feature, refactor

#318 Feature/gatherHub
  package-lock.json
  package.json
  src/app/api/auth/callback/route.ts
  src/app/api/gatherHub/route.ts
  src/app/eventsdetail/[id]/page.tsx
  src/app/eventsdetail/not-found.tsx
  src/app/gatherHub/page.tsx
  src/app/globals.css
  src/app/maindetail/not-found.tsx
  src/app/not-found.tsx
  src/components/Common/Header/Header.tsx
  src/components/Common/Loading/PuzzleAnimation.tsx
  src/components/GatherHub/JobDirectory.tsx
  src/components/GatherHub/MemberCard.tsx
  src/components/GatherHub/SkeletonCard.tsx
  src/components/MyPage/Common/LeftNav.tsx
  src/components/MyPage/MyInfo/ProfilePicture.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup04.tsx
  src/types/supabase.ts
Labels: update, feature, refactor

#321 refactor: hub페이지 전반적인 UI수정
  package-lock.json
  package.json
  public/assets/bookmark1.svg
  public/assets/bookmark2.svg
  public/assets/chat.svg
  src/app/gatherHub/page.tsx
  src/components/Common/Header/Header.tsx
  src/components/GatherHub/JobDirectory.tsx
  src/components/GatherHub/MemberCard.tsx
  src/components/GatherHub/SkeletonCard.tsx
  src/components/Signup/Signup01.tsx
Labels: refactor

#325 Fix/calender disable
  src/components/MainPage/MainSideBar/Calender/Calender.tsx
Labels: fix

#323 Refactor/signupform03
  src/app/globals.css
  src/components/Common/Header/Header.tsx
  src/components/Login/LoginForm.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup02.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/Signup04.tsx
  src/components/Signup/components/BlogInput.tsx
  src/components/Signup/components/CustomModal.tsx
  src/components/Signup/components/NicknameInput.tsx
  src/hooks/useSubmitProfile.ts
Labels: refactor

#331 Fix/deployment automation
  .github/workflows/deployment.yml
  build.sh
Labels: fix

#330 style: gatherHub페이지 간격조정 및 카드 css수정
  src/app/api/auth/callback/route.ts
  src/app/gatherHub/page.tsx
  src/components/Common/Header/Header.tsx
  src/components/GatherHub/JobDirectory.tsx
  src/components/GatherHub/MemberCard.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/components/AlertModal.tsx
Labels: style

#333 Update/prCard
  src/components/GatherHub/MemberCard.tsx
  src/components/MainPage/MainSideBar/PrCard/PrCard.tsx
Labels: update
