Repository gather-here/gather_here, pull requests merged in 2024-08, with the labels that each got.

#142 fix: 채팅 기능 최적화 #141
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
  src/components/MainPage/PageContent/AllContent.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
Labels: fix, Refactor

#144 Del/loadingDelete
  src/components/Login/LoginForm.tsx
  src/components/MainPage/InfiniteScroll/EventsInfiniteScroll.tsx
  src/components/MainPage/InfiniteScroll/InfiniteScrollComponents.tsx
Labels: Del

#149 Fix/image optimization disable
  .github/ISSUE_TEMPLATE/⚒️-refactor.md
  .github/ISSUE_TEMPLATE/✅update.md
  .github/ISSUE_TEMPLATE/✨style.md
  .github/ISSUE_TEMPLATE/🐞bug.md
  .github/ISSUE_TEMPLATE/📒feature.md
  .github/ISSUE_TEMPLATE/🔥del.md
  .github/ISSUE_TEMPLATE/🩹fix.md
  next.config.mjs
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
Labels: Fix

#146 fix:Feature/mainpage2
  public/Main/arrow.png
  public/Main/down.png
  public/Main/run.png
  public/assets/cardarrow.svg
  public/assets/down.svg
  public/assets/puzzle.svg
  public/assets/run.svg
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
  src/components/Common/Header/Header.tsx
  src/components/MainPage/FilterBar/FilterBar.tsx
  src/components/MainPage/PageContent/AllContent.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
Labels: fix

#174 Fix/deployment error
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
  src/components/MainPage/PageContent/ItEvent/Card/ItEventCardLong.tsx
  src/components/MainPage/PageContent/ItEvent/Card/ItEventCardShort.tsx
Labels: fix

#175 refactor/chat_post_login_verify
  src/components/Common/Header/Header.tsx
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
Labels: refactor

#176 Style/detailpage
  package-lock.json
  package.json
  src/app/(root)/maindetail/[id]/page.tsx
  src/app/(root)/post/(edit)/[id]/page.tsx
  src/app/(root)/post/page.tsx
  src/components/EventsDetail/ITLikeButton.tsx
  src/components/MainDetail/FormDropdown.tsx
  src/components/MainDetail/FormInput.tsx
  src/components/MainDetail/FormMultiSelect.tsx
  src/components/MainDetail/LikeButton.tsx
  src/components/MainDetail/ReactQuillEditor.tsx
  src/components/MainDetail/ShareButton.tsx
  src/components/MainDetail/custom-quill.css
Labels: style

#177 refactor/signup
  src/app/(root)/(auth)/login/logincallback/page.tsx
  src/assets/loadingBar.json
  src/components/Common/Loading/InitialLoadingWrapper.tsx
  src/components/Login/LoginForm.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup02.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/components/BlogInput.tsx
  src/components/Signup/components/NicknameInput.tsx
  src/hooks/empty.ts
  src/hooks/useCheckNickname.ts
  src/hooks/useSubmitProfile.ts
Labels: refactor

#178 Update/mypage and header chage svg
  package-lock.json
  public/Common/Icons/caution_icon.png
  public/Common/Icons/close.png
  public/Common/Icons/close_l.png
  public/Common/Icons/close_m.png
  public/Common/Icons/search.png
  public/Common/Icons/user.png
  public/Common/Icons/write.png
  public/MyPage/ProfileIcon/profileicon_01.jpg
  public/MyPage/ProfileIcon/profileicon_02.jpg
  public/MyPage/ProfileIcon/profileicon_03.jpg
  public/MyPage/ProfileIcon/profileicon_04.jpg
  public/MyPage/ProfileIcon/profileicon_05.jpg
  public/MyPage/ProfileIcon/profileicon_06.jpg
  public/MyPage/ProfileIcon/profileicon_07.jpg
  public/MyPage/ProfileIcon/profileicon_08.jpg
  public/MyPage/ProfileIcon/profileicon_09.jpg
  public/assets/header/close.svg
  public/assets/header/logo.svg
  public/assets/header/search.svg
  public/assets/header/user.svg
  public/assets/header/write.svg
  public/assets/mypage/hover_plus.svg
  public/assets/mypage/image_upload.svg
  src/app/(root)/mypage/loading.tsx
  src/components/Common/Card/PostCard/ItEventCardLong.tsx
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
  src/components/Common/Header/Header.tsx
  src/components/Layout/MainLayout.tsx
  src/components/MainPage/AdCard/AdCard.tsx
  src/components/MainPage/InfiniteScroll/InfiniteScrollComponents.tsx
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
  src/components/MainPage/NavTab/NavTabs.tsx
  src/components/MainPage/PageContent/AllContent.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
  src/components/MyPage/MyInfo/ProfilePicture.tsx
  src/components/MyPage/MyInterests/InterestsTap.tsx
  src/provider/UserContextProvider.tsx
Labels: update

#188 fix: 이미지 대체 경로 설정 #186
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
Labels: fix

#190 del: 불필요한 코드 삭제
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
Labels: del

#192 update: ascii art 추가
  src/components/Signup/Signup03.tsx
Labels: update

#201 Update/mypage mobile and hover
  public/assets/delete.svg
  public/assets/header/mobile_logo.svg
  public/assets/header/primary_close.svg
  src/app/(root)/globals.css
  src/app/(root)/maindetail/[id]/page.tsx
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
  src/components/Common/Header/Header.tsx
  src/components/Common/Skeleton/LeftNavLoader.tsx
  src/components/Common/Skeleton/MypageList.tsx
  src/components/MyPage/MyInfo/ProfileInfo.tsx
  src/components/MyPage/MyInfo/ProfilePicture.tsx
  src/components/MyPage/MyInterests/InterestsTap.tsx
  src/components/MyPage/MyPosts/PostsTap.tsx
  src/lib/fetchPosts.ts
Labels: update

#202 Refactor/make chat modal
  public/Chat/chat.svg
  public/Chat/close.svg
  public/Chat/people.svg
  public/Chat/send.svg
  public/assets/blank.svg
  src/app/(root)/(mainpage)/layout.tsx
  src/components/Layout/MainLayout.tsx
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
  src/components/MainPage/MainSideBar/Chat/ChatModal.tsx
  src/components/MainPage/MainSideBar/MainSideBar.tsx
  src/components/MainPage/PageContent/AllContent.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
  src/hooks/useChat.ts
  src/types/chats/Chats.type.ts
Labels: refactor

#214 Update/chat modal
  .github/ISSUE_TEMPLATE/⚒️refactor.md
  .github/ISSUE_TEMPLATE/✨style.md
  .nvmrc
  public/Chat/close.svg
  public/Chat/close_in_modal.svg
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
  src/components/MainPage/MainSideBar/Chat/ChatModal.tsx
  src/components/MainPage/MainSideBar/MainSideBar.tsx
  src/hooks/useChat.ts
Labels: update

#217 Feature/search 검색 기능 추가
  src/app/(root)/(mainpage)/all/page.tsx
  src/app/(root)/(mainpage)/events/page.tsx
  src/app/(root)/(mainpage)/projects/page.tsx
  src/app/(root)/(mainpage)/studies/page.tsx
  src/app/(root)/eventsdetail/page.tsx
  src/app/(root)/layout.tsx
  src/app/(root)/maindetail/page.tsx
  src/components/Common/Header/Header.tsx
  src/components/MainPage/InfiniteScroll/InfiniteScrollComponents.tsx
  src/components/MainPage/PageContent/AllContent.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
  src/hooks/useSearch.ts
Labels: feature

#222 update: update/mainpage_IT_Events
  src/components/Common/Card/PostCard/ItEventCardLong.tsx
  src/components/Common/Card/PostCard/ItEventCardShort.tsx
  src/components/MainPage/FilterBar/EventFilterBar.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/lib/fetchPosts.ts
Labels: update

#227 Bugfix/android
  src/components/Common/Card/PostCard/PostCardLong.tsx
  src/components/Common/Card/PostCard/PostCardShort.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/OAuthButtons.tsx
  src/components/MainPage/Carousel/Carousel.css
  src/components/MainPage/FilterBar/FilterBar.tsx
  src/components/MainPage/NavTab/NavTabs.tsx
  src/components/Signup/Signup01.tsx
  src/components/Signup/Signup02.tsx
  src/components/Signup/Signup03.tsx
  src/components/Signup/Signup04.tsx
  src/components/Signup/components/BlogInput.tsx
  src/components/Signup/components/NicknameInput.tsx
  tailwind.config.ts
Labels: fix

#242 update: 유효성수정, 프롬프트 추가 #229
  src/app/(root)/maindetail/[id]/page.tsx
  src/app/(root)/post/(edit)/[id]/page.tsx
  src/app/(root)/post/page.tsx
  src/hooks/useDraft.ts
  src/lib/validation.ts
Labels: update

#252 style/calender_qa_fix
  src/components/MainPage/MainSideBar/Calender/Calender.tsx
  src/components/MainPage/MainSideBar/Calender/fullcalender.css
Labels: style

#267 feature/not_found
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(mainpage)/all/page.tsx
  src/app/(mainpage)/events/page.tsx
  src/app/(mainpage)/layout.tsx
  src/app/(mainpage)/projects/page.tsx
  src/app/(mainpage)/studies/page.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/empty.ts
  src/app/api/events/route.ts
  src/app/eventsdetail/[id]/layout.tsx
  src/app/eventsdetail/[id]/modaltest/page.tsx
  src/app/eventsdetail/[id]/page.tsx
  src/app/eventsdetail/loading.tsx
  src/app/eventsdetail/not-found.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/maindetail/[id]/page.tsx
  src/app/maindetail/not-found.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/myinterests/page.tsx
  src/app/mypage/myposts/page.tsx
  src/app/mypage/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/post/(edit)/[id]/page.tsx
  src/app/post/page.tsx
Labels: feature

#269 fix: 불 필요한 코드 수정 #268
  src/app/api/auth/callback/route.ts
  src/app/api/empty.ts
  src/app/eventsdetail/[id]/modaltest/page.tsx
  src/app/eventsdetail/loading.tsx
  src/app/globals.css
  src/app/post/(edit)/[id]/page.tsx
  src/components/Common/Card/PostCard/ItEventCardLong.tsx
  src/components/Common/Card/PostCard/ItEventCardShort.tsx
  src/components/Common/Header/Header.tsx
  src/components/Common/Modal/CommonModal.tsx
  src/components/Common/Skeleton/MypageProfileInfo.tsx
  src/components/MainDetail/FormDropdown.tsx
  src/components/MainDetail/FormMultiSelect.tsx
  src/components/MainPage/Carousel/Carousel.css
  src/components/MainPage/Carousel/Carousel.tsx
  src/components/MainPage/Carousel/EventsCarousel.tsx
  src/components/MainPage/MainSideBar/Calender/Calender.tsx
  src/components/MainPage/MainSideBar/Calender/fullcalender.css
  src/components/MainPage/MainSideBar/Chat/Chat.tsx
  src/components/MainPage/MainSideBar/Chat/ChatModal.tsx
  src/components/MainPage/MainSideBar/PrCard/PrCard.tsx
  src/components/MainPage/PageContent/EventsContent.tsx
  src/components/MainPage/PageContent/ProjectContent.tsx
  src/components/MainPage/PageContent/StudiesContent.tsx
  src/components/MyPage/Common/LeftNav.tsx
  src/components/MyPage/MyInfo/ProfileInfo.tsx
  src/components/MyPage/MyInterests/InterestsTap.tsx
  src/components/Signup/Signup01.tsx
  src/hooks/useChat.ts
  src/hooks/useCheckNickname.ts
  src/lib/fetchPosts.ts
  src/middleware.ts
  src/provider/ContextProvider.tsx
  src/provider/QueryClientProvider.tsx
  src/store/useSignupStore.ts
  tailwind.config.ts
Labels: fix
